import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout';
import { Toaster } from '@/components/ui/toaster';

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`} 
        suppressHydrationWarning
      >
        <Header />
        <main className='pt-24 w-full min-h-screen flex flex-col'>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
